### PR TITLE
Update tcl

### PR DESCRIPTION
**Pull request by shot0829**
huge changes to tcl files:
1. reformatted indent
2. created functions and loops to enable rha_central_diff and other algorithms to run after newton failed

a minor fix in Taghavi_Miranda_2005.py

### CODE REVIEW

**Review by jasonmotha — APPROVED** [review]
I'm generally not a fan of test data on the repo - especially when the folder is called large.

I also presume you have tested the changes and these were the changes that Vahid made?

**Comment by shot0829** [comment]
> I'm generally not a fan of test data on the repo - especially when the folder is called large.
> 
I get your point. but these waveforms are so small at the moment, I think its fine.
If the test become more complicated and grew in size, then we can then figure out a better way.
(sidenote: I'm personally more tend towards input/output of test data in repo if possible, this enables us to update the test more easily if its outdated. instead of pack then repack a the package on AWS and ask sung to update.
pros and cons on both method, but thats off-topic for now)

> I also presume you have tested the changes and these were the changes that Vahid made?
yes, i recieved a package of updated codes from vahid, and reformatted the indent.
I also tested all models one by one.

**Comment by jpa198** [comment]
@shot0829 Part of running jenkins ourselves is that the test data is hosted in a folder on our AWS. Ask @sungeunbae for the ftp details, and you can upload more test data/outputs

**Review by jpa198 — COMMENTED** [review]
Generally approve, should either move the test data to AWS or give the folder a more descriptive name though.
I'll accept the tcl scripts on faith that you and Vahid know what you're doing with them, and that you'll be the ones to pick them up something goes wrong with them

**Review by jpa198 — DISMISSED** [review]

**Comment by jasonmotha** [comment]
Watiing on 
> either move the test data to AWS or give the folder a more descriptive name though.

**Review by jpa198 — APPROVED** [review]

**Review by jasonmotha — APPROVED** [review]

**Pull request merged**
