### PR TITLE
forced the version of numba, to solve a llvmlite crash issue on nurion

### PR DESCRIPTION
**Pull request by shot0829**

### CODE REVIEW

**Review by jasonmotha — CHANGES_REQUESTED** [review]
I'm also not sure that this place is the best to fix this issue for one platform as it influences all the platforms?

I think we still need numpy on the list?
It would be good to have a '>=' on numba so that it isn't limited to that version until we notice it again.

**Comment by shot0829** [comment]
> I'm also not sure that this place is the best to fix this issue for one platform as it influences all the platforms?
> 
> I think we still need numpy on the list?
> It would be good to have a '>=' on numba so that it isn't limited to that version until we notice it again.

i removed numpy because it is required for numba.

**Comment by shot0829** [comment]
will it be better if i use >= instead of ==?
the issue was for some reason pip's default version is not the latest and installed a old version which caused all kinds of trouble.

**Comment by shot0829** [comment]
nevermind, i missed the line in your comment that suggested >=

**Comment by sungeunbae** [comment]
> > I'm also not sure that this place is the best to fix this issue for one platform as it influences all the platforms?
> > I think we still need numpy on the list?
> > It would be good to have a '>=' on numba so that it isn't limited to that version until we notice it again.
> 
> i removed numpy because it is required for numba.

As numba was picky with the version of numpy, removing numpy and letting numba decide the version of numpy appears to be a clever workaround to me.

**Review by jpa198 — APPROVED** [review]
I don't think setting a minimum level is a bad thing

**Review by sungeunbae — APPROVED** [review]

**Review by jasonmotha — APPROVED** [review]

**Pull request merged**
