### PR TITLE
Advanced im trunk

### PR DESCRIPTION
**Pull request by jpa198**
Just to keep an eye on the current diff

### CODE REVIEW

**Comment by jpa198** [comment]
I recommend filtering out .mat and .tcl files when viewing the diff

**Comment by jasonmotha** [comment]
@shot0829 (@jpa198 ) Why did this get merged?

**Comment by jpa198** [comment]
@jasonmotha Was everything in this PR also in #95 ?

**Comment by jpa198** [comment]
Otherwise, how did this get merged? No one would have overridden the safeties for this to go in

**Comment by jpa198** [comment]
Yeah, looking at the network graph this was upstream of #95 and so Git 'helpfully' marked it as done without further comment

**Comment by shot0829** [comment]
#95  was a fork out of the base #94 .
#94 is the upstream of 95 with any changes

**Pull request merged**
