### PR TITLE
Adding SDOF_IMK

### PR DESCRIPTION
**Pull request by sungeunbae**
Added a new adv_im model, and tested with
```
(python3_maui) baes@maui02: ~/IM_calculation$ bash IM_calculation/test/opensees_advanced_im.sh SDOF_IMK large
```
small, moderate and large all passed.

### CODE REVIEW

**Comment by jpa198** [comment]
Was testing output compared against data provided by Vahid, or that the model ran without crashing?

**Comment by sungeunbae** [comment]
> Was testing output compared against data provided by Vahid, or that the model ran without crashing?

haha - very sharp. will check with him and give you an update. Vahid is not comfortable with switching between branches, so I will be doing the test myself.

**Review by jasonmotha — COMMENTED** [review]
Generally happy with the code. Will wait for Vahid's testing data.

**Comment by jasonmotha** [comment]
@sungeunbae Any update on this?

**Comment by jpa198** [comment]
Vahid has approved the model

**Review by jpa198 — APPROVED** [review]

**Review by jasonmotha — APPROVED** [review]

**Pull request merged**
